FROM containernet/containernet

RUN apt update

RUN apt install -y x11-xserver-utils

RUN apt install -y ifupdown net-tools

RUN apt install -y tcpdump

RUN apt install -y ftpd vim

RUN apt-get install -y xinetd telnetd telnet